admin:
  masterkey: empty1

config:
  urlProducts: products
  urlCategories: categories

management:
  endpoints.web.base-path: /actuator
  server.port: 80
  health:
    mail:
      enabled: false
  endpoint:
    health:
      show-details: when-authorized
  endpoints:
    web:
      exposure:
        include: health, info, refresh, shutdown, env
        
spring:
  data:
    mongodb:
      products:
        host: <mongodb url>
        port: 27017
        database: products
        username: <mongodb user>
        password: empty2
      employees:
        host: <mongodb url>
        port: 27017
        database: employees
        username: <mongodb user>
        password: empty2
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration,org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

server:
  port : 80